### ISSUE TITLE
Set up GitHub actions to run tests for each PR

### ISSUE THREAD

**Issue by kubk** [terrasoff/ts-mobx-form-state#9]
If someone creates a GitHub PR to the library it's better to know if their changes break tests or not. GitHub actions can be used for this purpose. Can make a PR

**Comment by terrasoff** [comment]
At the moment the library has [bitbuckets pipelines](https://github.com/terrasoff/ts-mobx-form-state/blob/master/bitbucket-pipelines.yml). Would be great to move to github actions! Contributing is welcome, Appreciate that!
